### ISSUE TITLE
How to adjust lineskip in algorithmic?

### ISSUE THREAD

**Issue by note286** [chrmatt/algpseudocodex#12]
I need to modify the `lineskip` value in a certain `algorithmic` environment so that it applies uniformly throughout the environment. It works in the `algpseudocode` package, but not in the `algpseudocodex` package. In the `algpseudocodex` package, I have to manually set it after each `\State`, which is very inconvenient. I have roughly read the source code, but I haven't found the reason. It seems like `\State` is resetting some values.

```latex
\documentclass{article}
% \usepackage{algpseudocodex}
\usepackage{algpseudocode}
\begin{document}
\begin{algorithmic}[1]
\addtolength{\lineskip}{10pt}
\Require
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
$\sum\limits_i^1$
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
\Ensure
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
$\sum\limits_i^1$
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
\State
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
$\sum\limits_i^1$
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
\State
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
\State
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
$\sum\limits_i^1$
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
\end{algorithmic}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/232078296-3752887e-b2cb-4e37-98b7-d75c2d7b587e.png)

---

But if with `algpseudocodex`.

![image](https://user-images.githubusercontent.com/16207292/232078430-e8f15edb-1f9d-4872-9ccd-089bcea94f43.png)

---

With `algpseudocodex`, must add after to `\State`.

```latex
\State \addtolength{\lineskip}{10pt}
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
$\sum\limits_i^1$
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

![image](https://user-images.githubusercontent.com/16207292/232080132-cc9ccd91-a150-4a84-8f78-a9dd2108a3f5.png)

**Comment by note286** [comment]
After testing, I found that the `\lineskip` value set outside does not take effect within the `minipage`.

**Comment by chrmatt** [comment]
Your testing is correct: The reason it does not work with algpseudocodex is that it places everything in a varwidth environment, which resets certain values. You can place the following at the beginning of the algorithmic environment:
`\makeatletter\pretocmd{\algpx@endCodeCommand}{\addtolength{\lineskip}{10pt}}{}{}\makeatother`
This changes the lineskip for every command.

**Comment by note286** [comment]
If `noEnd=true`, the position of the end will be added twice. If `noEnd=false`, It seems like there's no problem.

```latex
\documentclass[twocolumn]{article}
\usepackage[noEnd=true]{algpseudocodex}
\makeatletter
\pretocmd{\algpx@endCodeCommand}{\addtolength{\lineskip}{10pt}}{}{}
\makeatother
\newcommand{\xxx}{Lorem ipsum dolor sit amet $\sum\limits_i^1$}
\begin{document}
\begin{algorithmic}[1]
\Require \xxx
\Ensure \xxx
\For{\xxx}
\For{\xxx}
\State \xxx
\EndFor
\State \xxx
\EndFor
\State \xxx
\State \xxx
\State \xxx
\end{algorithmic}
\newpage
\begin{algorithmic}[1]
\Require \xxx
\Ensure \xxx
\State \xxx
\State \xxx
\State \xxx
\State \xxx
\State \xxx
\State \xxx
\State \xxx
\end{algorithmic}
\newpage
\begin{algorithmic}[1]
\Require \xxx
\Ensure \xxx
\For{\xxx}
\State \xxx
\State \xxx
\State \xxx
\EndFor
\State \xxx
\State \xxx
\State \xxx
\end{algorithmic}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/232315154-27024c8e-7d21-4b9f-a833-046c894ede71.png)

---

`noEnd=false`

![image](https://user-images.githubusercontent.com/16207292/232315273-854f4ff0-7e78-43a2-866e-d2abd3277e44.png)

**Comment by note286** [comment]
The following configuration results are good, I'm not sure if there are any omissions in principle? As the author, you are more familiar with the implementation details.

```latex
\usepackage[noEnd=true]{algpseudocodex}
\AtBeginEnvironment{algorithmic}{
\apptocmd{\State}{\addtolength{\lineskip}{10pt}}{}{}
\addtolength{\lineskip}{10pt}
}
```

![image](https://user-images.githubusercontent.com/16207292/232318656-ede2552c-f624-4d7d-b5a3-9f7261a5ffb9.png)

**Comment by chrmatt** [comment]
If you just modify `\State`, it will not affect text inside, for, if, etc., that is spanning multiple lines.

I've pushed a quick update to the package such that the lineskip value is automatically restored. You can try the newest version from GitHub, it should behave the same as `algpseudocode`. It should be available via CTAN as version 1.1.1 soon.

**Comment by note286** [comment]
Thank you very much. Considering the actual use, we still need to restore the value of `\lineskiplimit`. I have submitted the PR.

**Comment by chrmatt** [comment]
Great, thank you!
