### ISSUE TITLE
Compile error with MacTeX 2024 on Mac OS Ventura

### ISSUE THREAD

**Issue by KeithDevlin** [chrmatt/algpseudocodex#21]
I have a MacBook running Monterey and another running Ventura, synched over iCloud. (So all my TeX files are identical.)
MacTeX 2024 runs perfectly on the Monterey machine. But when running MacTeX 2024 on Ventura with the identical project folder,   \pageref   does not display the pages in the PDF output. As far as I can tell, that is the only thing that fails in the Ventura compile. Everything else comes out fine on either machine. (Yes, I know you have to compile twice.) I’ve tried deleting the aux file on Ventura but that does not fix the issue. (The aux file DOES have all the pageref data on Ventura. But LaTeX doesn't read them; or at least does not print them in the output file.) Presumably this is a pathway problem that results from running in Ventura (so likely a MacOS file-system issue); but that's beyond my ken.

**Comment by chrmatt** [comment]
Are all your packages up to date? Did it work before on that machine? This sounds like a general issue with your LaTeX installation and not specific to algpseudocodex.

**Comment by KeithDevlin** [comment]
I tried replacing the MacTeX 2024 package with MacTeX 2015 (I had an old installer sitting around) and everything runs fine on both devices.  Looks like there is an issue with 2024 and Ventura. For me the problem is solved. Thanks for the response.
