### ISSUE TITLE
Indent guide lines extended over pagebreak

### ISSUE THREAD

**Issue by dantetante** [chrmatt/algpseudocodex#4]
It would be cool if the indent guide lines would respect pagebreaks. I documented this here: [https://tex.stackexchange.com/questions/620301/problem-with-page-break-and-indent-guide-lines-of-package-algpseudocodex]

I found this, which shows what behaviour I have in mind:[https://texwelt.de/fragen/23135/pagebreak-mit-einschrankungen]

**Comment by ghost** [comment]
Any progress on this? I have the same problem and this package doesn't seem to receive any more updates as of now.

**Comment by chrmatt** [comment]
Unfortunately, I haven't had time to work on this recently. I hope to find some time to fix this in the next weeks.
